src/main/webapp/assets/js/utils.js, src/main/webapp/index.html
for https://jira.it.umich.edu/browse/TLUNIZIN-483
=> TLUNIZIN-483 - add mor eclarity to the interaction when crosslisting

src/main/webapp/assets/js/utils.js
for
https://jira.it.umich.edu/browse/TLUNIZIN-482
=> TLUNIZIN-482 - replace xlist messages, instead of appending them

src/main/webapp/assets/js/utils.js
https://jira.it.umich.edu/browse/TLUNIZIN-487
https://jira.it.umich.edu/browse/TLUNIZIN-486
small changes for both
=> TLUNIZIN-487 and TLUNIZIN-487

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/resources/sectiontool.properties, src/main/webapp/assets/js/utils.js, src/main/webapp/index.html
for 
https://jira.it.umich.edu/browse/TLUNIZIN-444
=> Tlunizin 444

src/main/webapp/assets/js/utils.js
Moved handler for xlisting posts out of the handler for opening a dialog box (what was I thinking if anything), keeping the scopes separate.
=> TLUNIZIN-519 - take two

README.md, pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/CheckAccountExistsResponse.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/CreateAccountResponse.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Friend.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/FriendServlet.java, src/main/resources/friendEmail.template, src/main/resources/requesterEmail.template, src/main/resources/sectionsToolFriend.properties.template, src/main/resources/sectionsToolFriendSecure.properties.template, src/main/webapp/WEB-INF/web.xml
Due: 7/17/2015
@dlhaines 
@pushyamig
=> TLUNIZIN-559 Create backend for Friend Account Management

src/main/webapp/assets/js/controllers/controllers.js, src/main/webapp/assets/js/utils.js, src/main/webapp/index.html
... and that was the cause of this regression.
=> TLUNIZIN-635 - do not use Angular scope in jQuery panels

src/main/java/edu/umich/ctools/sectionsUtilityTool/FriendServlet.java, src/main/resources/friendEmail.template, src/main/resources/requesterEmail.template, src/main/webapp/assets/js/controllers/controllers.js
Update Email templates. 
Update http response from servlet when adding friend accounts.
Due: 08/06/2015
@gsilver
=> TLUNIZIN-666 Bug Fixes

pom.xml
Updating version number from 2.0.0 to 2.0.1
=> Updated version from 2.0.0 to 2.0.1

src/main/java/edu/umich/ctools/sectionsUtilityTool/Friend.java
=> TLUNIZIN-720 clean up properties

README.md
=> TLUNIZIN-728 Update README file

pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/resources/mpathwaysSample.txt
Due: 10/19/2015
@dlhaines 
@pushyamig
=> TLUNIZIN-783 Create API that returns Test Data for MPathWays call

pom.xml
=> Updated POM to reflect project name

.gitignore, pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
DUE: 10/27/2015
@dlhaines 
@pushyamig
=> [TLUNIZIN-747] Create API that returns actual Course/Term data from ESB/MPathways

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/utils.js, src/main/webapp/assets-lti/views/course.html, src/main/webapp/assets-lti/views/friends.html, src/main/webapp/index-lti.vm
From branch [/gsilver/canvas_course_manager/tree/TLUNIZIN-737f](/gsilver/canvas_course_manager/tree/TLUNIZIN-737f).
=> TLUNIZIN-737

README.md, pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 11/6
@dlhaines 
@pushyamig
=> TLUNIZIN-743 The Faculty facing functionality will only be launched as an LTI Tool

src/main/webapp/build.txt, src/main/webapp/status.html, src/main/webapp/status/ping.html
=> TLUNIZIN-681 Create /status URLs for Canvas Course Manager

src/main/webapp/assets-lti/css/custom_style.css, src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/factories/factories.js, src/main/webapp/assets-lti/js/services/services.js, src/main/webapp/assets-lti/views/course.html, src/main/webapp/assets-lti/views/friends.html
Low hanging a11y fruit.  Details at https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-742
=> Tlunizin 742f

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java
Due: 11/12/2015
@dlhaines 
@pushyamig
=> TLUNIZIN-743 Bug fix for LTI Launch

src/main/webapp/assets-lti/css/custom_style.css, src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/utils.js, src/main/webapp/assets-lti/views/course.html, src/main/webapp/assets-lti/views/friends.html
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-812
Opted for doing all of the work in the subtasks against the umbrella task.
=> TLUNIZIN-812 - redesign as response to user feedback

src/main/webapp/assets-lti/js/controllers/controllers.js
for 
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-830
=> TLUNIZIN-830 - identify UM term id correctly

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/factories/factories.js, src/main/webapp/assets-lti/js/utils.js, src/main/webapp/assets-lti/views/course.html
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-831
=> Tlunizin 831

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/factories/factories.js, src/main/webapp/assets-lti/js/utils.js, src/main/webapp/assets-lti/views/friends.html, src/main/webapp/index-lti.vm
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-843
=> Tlunizin 843

src/main/webapp/assets-lti/css/custom_style.css
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-862
=> TLUNIZIN-862 - set alert text to #000 to get WCAG 2 AAA contrast

pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/webapp/assets-lti/js/controllers/controllers.js
Due: Dec 7th
@dlhaines 
@pushyamig 
@gsilver
=> TLUNIZIN-799 and 824 Mask APIs and Fix Help Page in LTI

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/views/course.html
for
https://jira.it.umich.edu/browse/TLUNIZIN-868
=> TLUNIZIN-868 - fix filtering of other courses

src/main/webapp/help.html
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-746
=> TLUNIZIN-746 - add help content

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/factories/factories.js
Due: 12/17
@gsilver 
@dlhaines 
@pushyamig
=> TLUNIZIN-875 Mask Course Id in API calls

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
=> TLUNIZIN-874 Modify logging for CCM

src/main/webapp/assets-sc/js/controllers/controllers.js
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-902
=> Tlunizin 902

src/main/webapp/assets-lti/views/friends.html
Sorry about wspace changes - all that was really changed is the ng-hide directive
=> TLUNIZIN-909 - use ng-if instead of ng-hide

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 01/11
@dlhaines 
@pushyamig
=> TLUNIZIN-880 Do not allow crosslist requests that the user is not authorized to make

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 01/19
@pushyamig 
@dlhaines
=> TLUNIZIN-875 Mask Course Id in API Call

src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java, src/main/resources/stubs/canvas/users.txt
Due: 1/22
@pushyamig 
@dlhaines
=> TLUNIZIN-905 Update CCM Stubs to be consistenet with changes related to pen testing

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 1/27
@pushyamig 
@dlhaines
=> TLUNIZIN-886 Status Page Requires Authentication

src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java
=> TLUNIZIN-874 Improved Logging for Stub

pom.xml
=> TLUNIZIN-926 Tag CCM 3.0

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due Date: 3/9
@dlhaines 
@pushyamig
=> TLUNIZIN-849 Remove hard coded lti key

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/utils.js
@dovek 
for subtask 
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-955
Change to regex
canvas.api.get.single.course.enrollment.regex=^/api/v1/courses/course_id/enrollments\\?type\=TeacherEnrollment&type=DesignerEnrollment&user_id=.*&_=\\d+$
=> Tlunizin 955

src/main/webapp/assets-lti/js/controllers/controllers.js
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-960
=> TLUNIZIN-960 - make Canvas API request less restrictive

pom.xml
=> TLUNIZIN-897

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/factories/factories.js, src/main/webapp/assets-lti/js/utils.js, src/main/webapp/assets-sc/js/controllers/controllers.js, src/main/webapp/assets-sc/js/factories/factories.js, src/main/webapp/assets-sc/js/utils.js
for
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-961
=> TLUNIZIN-961 - specify what regex urls are using

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/js/utils.js
Due: 3/24/2016
@dlhaines 
@gsilver
=> TLUNIZIN-853 Tool should be usable by friends

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
=> TLUNIZIN-956 Use new enrollment API to grant add access to Librarians

src/main/webapp/status
=> TLUNIZIN-952 modified status page to reflect change in ping

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 3/25/2016
@gsilver 
@dlhaines
=> TLUNIZIN-910 fixed bug for enrollments call

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 4/6/2016
@gsilver 
@dlhaines
=> TLUNIZIN-977 Add custom_canvas_user_id value to session data

src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/index-lti.vm
See:
https://itsjira.umms.med.umich.edu/browse/TLUNIZIN-982
@dovek
=> TLUNIZIN-982 - remove fuzzy search call not needed

src/main/webapp/assets-lti/js/utils.js
=> TLUNIZIN-956-2 modified role to search for in friend menu

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 4/8
@pushyamig 
@dlhaines
=> TLUNIZIN-954 CCM should read permissions for Canvas roles from properties file

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 04/13
@dlhaines 
@pushyamig
=> TLUNIZIN-983 Add roles that can add teacher values to session

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 4/13
@pushyamig 
@dlhaines
=> TLUNIZIN-981 Servlet modifies link header before passing to front ui

pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 4/21
@pushyamig 
@dlhaines
=> TLUNIZIN-990 Set different replacements for SC LTI

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
Due: 4/27
@dlhaines 
@pushyamig
=> TLUNIZIN-1000 TAs cannot add students to course

src/main/webapp/assets-lti/js/controllers/controllers.js
=> TLUNIZIN-999 - remove dupes before adding them to scope

src/main/webapp/assets-lti/js/factories/factories.js, src/main/webapp/assets-sc/js/controllers/controllers.js, src/main/webapp/assets-sc/js/factories/factories.js
for
[TLUNIZIN-1004] LTI Version: Instructor cannot see all courses (paging?) 
and
[TLUNIZIN-978] Use link header paging info in page 
[TLUNIZIN-988] Make SC version paging-capable
=> Tlunizin 1004

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java
=> TLUNIZIN-1003 Add users to multiple sections with multiple roles

src/main/java/edu/umich/ctools/sectionsUtilityTool/FriendServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java
=> CCM3-13 adding admin check

README.md, pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionUtilityToolFilter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/test/scripts/settings.sh, src/test/scripts/test-curl.sh
=> CCM3-100 Pointing to new API manager in WAPI

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/ToolAccessGranter.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java
=> CCM3-104 adding role check to get access to the tool

Dockerfile
=> CCM3-108 Dockerfile changes for new secret for adhoc tomcat related file

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java, src/main/webapp/index-lti.vm, src/main/webapp/index-sc.vm
https://itsjira.umms.med.umich.edu/browse/CCM3-101
=> CCM3-101 adding Openshit build info to UI

src/main/webapp/assets-lti/views/saa.html
…Enrollment
For https://itsjira.umms.med.umich.edu/browse/CCM4-5
=> CCM4-10 - track section list by index to avoid ngular errors

src/main/java/edu/umich/ctools/sectionsUtilityTool/SectionsUtilityToolServlet.java, src/main/webapp/assets-lti/js/controllers/controllers.js, src/main/webapp/assets-lti/views/course.html
New regex
#GET 
#/api/v1/courses/211644/sections?_=1516113120687&page=2&per_page=100 
canvas.api.getallsections.per.course.paged.regex=^/api/v1/courses/\\d+/sections\\?_=\\d+&page=\\d+&per_page=\\d+
=> Ccm4 7 - paged sections request

src/main/java/edu/umich/ctools/sectionsUtilityTool/SISPollingThread.java, src/main/resources/slowprocess-email.template
=> Adding sis job id to email report

pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/FriendServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java
=> #273 sending the cirrus sponsored no reply email address

pom.xml
=> Change the logging packge to  log4j2

pom.xml, src/main/java/edu/umich/ctools/sectionsUtilityTool/FriendServlet.java, src/main/java/edu/umich/ctools/sectionsUtilityTool/Utils.java
Fixes #283 
Making this as a configurable option so that Prod/test subject line has a difference
=> #283 change the social login email subject line
